#!/bin/sh

# JIM: change to take an argument for full vs incremental
#  change both full and incremental to use find command to get list of
#  files to back.
# Incremental should use date of last full backup to get newer files.
# Also figure out if compression is working!

filename=`date "+%Y.%m.%d-%H.%M"`
target=/Volumes/jak/MacBackups

#archive=$target/full.${filename}.tar	# for full backup
archive=$target/inc.${filename}.tar	# for incremental backup

echo backing up to:  $archive
cd		# to home directory

# for incrementals
find -f		\
./bin		\
./Desktop	\
./other		\
./Documents	\
./lib		\
./manager	\
./personal	\
./oboedit_config \
./Signatures	\
./work		\
-not -path "*/Microsoft User Data/*" \
-not -path "*/Statsitics_I/Videos/*" \
-type f -newer  $target/2014.04.17-09.35.tar  > /tmp/jakfilelist

tar cvf ${archive} -z -T /tmp/jakfilelist
rm -f /tmp/jakfilelist

exit 0
# full backup
tar cvf ${archive} -z  \
--exclude "Documents/Microsoft User Data/" \
--exclude "Statistics_I/Videos/" \
./bin ./Desktop ./dev ./Documents ./lib ./manager ./personal ./oboedit_config ./Signatures ./work

